### ISSUE TITLE
Error: [-100009] Invalid procedure call.

### ISSUE THREAD

**Issue by charliex2** [anlebcoder/extract-js-contract#1]
执行 fibos index.js 报如下错误。

```javascript
/Users/charlie/Code/demo/extract-js-contract/lib/index.js:40:10
        zipfile.extractAll(path)
                ^
Error: [-100009] Invalid procedure call.
    at module.exports (/Users/charlie/Code/demo/extract-js-contract/lib/index.js:40:10)
    at /Users/charlie/Code/demo/extract-js-contract/index.js:3:1
```

index.js 
```javascript
let lib = require("./lib");

lib("fibosmonitor", {
	env: "mainnet",
	path: "./dapppath"
});

```

**Comment by anlebcoder** [comment]
可能是 path 路径没有创建，如果没有解决，把fibos 版本贴出来， `fibos --v`

**Comment by charliex2** [comment]
> 可能是 path 路径没有创建，如果没有解决，把fibos 版本贴出来， `fibos --v`

路径应该已经创建了。不过路径已经存在的情况下，执行 fibos index.js 会报错，所以我注释了 lib/index.js 的第 33 行：
```js
	// fs.mkdir(path);
```
文件目录：
```shell
➜  extract-js-contract git:(master) ✗ tree
.
├── README.md
├── dapppath
│   └── abi.json
├── examples
│   ├── dapp
│   │   ├── abi.json
│   │   └── code
│   │       ├── index.js
│   │       └── lib
│   │           ├── action.js
│   │           └── db.js
│   └── index.js
├── index.js
├── lib
│   └── index.js
├── package-lock.json
└── package.json

```

Fibos version: 
```shell
v0.27.0-dev
```
